### PR TITLE
PARQUET-173: Fixes `StatisticsFilter` for `And` filter predicate

### PR DESCRIPTION
**Pull request by liancheng**
[Review on Reviewable](https://reviewable.io/reviews/apache/incubator-parquet-mr/108)

### CODE REVIEW

**Comment by liancheng** [comment]
@isnotinvain Would you mind to help review? Thanks.

**Comment by tianyi** [comment]
@tsdeng

**Comment by julienledem** [comment]
+1 LGTM :)
@isnotinvain: what do you think?

**Comment by isnotinvain** [comment]
+1, nice catch, had to think about it again to make sure but this looks correct :)

**Pull request closed without merging**
