### PR TITLE
PARQUET-111: Updates for apache release

### PR DESCRIPTION
**Pull request by rdblue**
Updates for first Apache release of parquet-mr.

### CODE REVIEW

**Comment by rdblue** [comment]
@julienledem @tomwhite could you take a look at this? I think it is ready for review. We will need to get a +1 from @wesleypeck and @lukasnalezenec to [move the header copyrights to NOTICE](https://www.apache.org/legal/src-headers.html#3party), but I think other than that this is ready to merge. Thanks!

**Comment by rdblue** [comment]
There's more info on [PARQUET-111](https://issues.apache.org/jira/browse/PARQUET-111) as well, in case there are questions.

**Comment by julienledem** [comment]
LGTM. +1
Your stats on the number of line changed are going to jump!

**Comment by tomwhite** [comment]
+1

**Comment by lukasnalezenec** [comment]
Hi
+1, You can move my copyrights to notice.
Lukas

**Comment by rdblue** [comment]
I've updated this PR and removed the parquet-tools header changes. That way, I can merge most of this before master changes completely. Once the tests complete, I'll merge it and submit the parquet-tools changes as a separate PR. Thanks for the reviews, everyone!

**Pull request closed without merging**
