### PR TITLE
PARQUET-206: fix MapredParquetOutputCommiter

### PR DESCRIPTION
**Pull request by tsdeng**

### CODE REVIEW

**Comment by rdblue** [comment]
This is still failing with the hadoop-2 profile for me:

```
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.547 sec <<< FAILURE!
testWrite(parquet.cascading.TestParquetTBaseScheme)  Time elapsed: 5.179 sec  <<< ERROR!
cascading.flow.FlowException: local step failed
  at cascading.flow.planner.FlowStepJob.blockOnJob(FlowStepJob.java:219)
  at cascading.flow.planner.FlowStepJob.start(FlowStepJob.java:149)
  at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:124)
  at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:43)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by tsdeng** [comment]
I tested it in intelliJ, and it worked fine.....weird

**Comment by tsdeng** [comment]
Even the mvn test -P hadoop2 command passed locally for me.

**Comment by rdblue** [comment]
It succeeds in IntelliJ for me, but not from the command line. Could you try with this:

```
mvn test -P hadoop-2
```

The profile name has a - in it, so maybe it wasn't picking up the profile for you.

**Comment by tsdeng** [comment]
fixed and merged in https://github.com/apache/incubator-parquet-mr/pull/141

**Pull request closed without merging**
