### PR TITLE
PARQUET-124: normalize path checking to prevent mismatch between URI and ...

### PR DESCRIPTION
**Pull request by chrisalbright**
...path

### CODE REVIEW

**Comment by chrisalbright** [comment]
how embarrasing :/ I have been checking on the JIRA ticket but not here. I'll update the commit message, and re-push, but will that be a problem for you trying to merge?

**Comment by chrisalbright** [comment]
how embarrasing :/ I have been checking on the JIRA ticket but not here. I'll update the commit message, and re-push, but will that be a problem for you trying to merge?

**Comment by rdblue** [comment]
No, it should be fine. Would you mind rebasing on master? That would make it much easier to pull.

**Comment by chrisalbright** [comment]
Ok @rdblue commit message re-written - sorry for the d-e-l-a-a-a-y

**Comment by julienledem** [comment]
@rdblue did you want to merge?

**Comment by rdblue** [comment]
Merged! Thanks @chrisalbright!

**Pull request closed without merging**
